server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://49.234.141.251:3306/hhelpApp?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: xiegang224

logging:
  file:
    name: my.log
  level:
    com.hhelp.mapper: info
    o.m.s.mapper.ClassPathMapperScanner: info
    com.hhelp.HhelpApplication: info
    com.hhelp.controller: info

mybatis:
  type-aliases-package: com.hhelp.domain

